# Introduction

This document describes the processes and methods we use to assess and evaluate the BYU Civil Engineering (BS) program. ABET criterion 4 states: 

> The program must regularly use appropriate, documented processes for assessing and evaluating the extent to which the student outcomes are being attained. The results of these evaluations must be systematically utilized as input for the program's continuous improvement actions. Other available information may also be used to assist in the continuous improvement of the program.

This manual documents these processes and provides a record of historical assessment data. 
The program uses five categories of assessments:

  1. Direct assessment of student outcomes in course assignment (see @sec-so)
  2. Student performance on the Fundamentals of Engineering (FE) exam (see @sec-fe)
  3. Graduation surveys and exit interviews (see @sec-exit)
  4. Student course evaluations (see @sec-eval)
  5. Statistics on student progress in the major (see @sec-progress)

## Evaluation and Continuous Improvement Process
Each summer, the CE undergraduate committee evaluates recent assessment data.
The evaluation process results in a determination of the program's strengths and weaknesses. 
The process also recommends actions to resolve the identified weaknesses.
Potential actions may include changes to the following:

  - program courses, requirements, or prerequisites 
  - course content or learning activities
  - course assessments
  - performance indicators or associated rubrics
  
The undergraduate committee documents the assessment evidence, evaluated strengths and 
weaknesses, and proposed actions in the program stewardship report. 
This report is reviewed by the department faculty and approved in a meeting before August 31 of the 
year of the report.

The undergraduate committee takes responsibility to implement the recommended actions.
Changes to program courses, requirements, or prerequisites are approved by faculty vote and
submitted to the university curriculum committee and registrar for approval.
When recommending changes to courses or course activities, the program committee
works closely with the course instructors to design and implement the proposed
actions.

Individual instructors make improvements to course activities, pedagogy, and content based
on data obtained through direct experience and student evaluation comments. These
are important data that may lead to recommended course and program changes, but are not a
formal assessment tool.
